version: "1"
services:
  - type: web
    name: strawpoll-backend
    env: python
    rootDir: backend
    plan: free
    region: singapore
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: changeme123
      - key: DATABASE_URL
        sync: false
